version: '3.8'

services:
  citus_coordinator:
    image: citusdata/citus:12.0
    container_name: citus_coordinator
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - citus-coordinator-data:/var/lib/postgresql/data
      - ./infrastructure/citus-cluster/postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      citus-network:
        ipv4_address: 172.25.0.2

  citus_worker1:
    image: citusdata/citus:12.0
    container_name: citus_worker1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - citus-worker1-data:/var/lib/postgresql/data
      - ./infrastructure/citus-cluster/postgres-init/01-worker-init.sh:/docker-entrypoint-initdb.d/01-worker-init.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      citus-network:
        ipv4_address: 172.25.0.3

  citus_worker2:
    image: citusdata/citus:12.0
    container_name: citus_worker2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - citus-worker2-data:/var/lib/postgresql/data
      - ./infrastructure/citus-cluster/postgres-init/01-worker-init.sh:/docker-entrypoint-initdb.d/01-worker-init.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      citus-network:
        ipv4_address: 172.25.0.4
  
  citus_setup:
    image: citusdata/citus:12.0
    container_name: citus_setup
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./infrastructure/citus-cluster/postgres-init/setup-scripts:/setup-scripts
    depends_on:
      citus_coordinator:
        condition: service_healthy
      citus_worker1:
        condition: service_healthy
      citus_worker2:
        condition: service_healthy
    command: >
      bash -c "cd /setup-scripts && 
               chmod +x ./setup-cluster.sh && 
               chmod +x ./setup-telemetry-table.sh && 
               ./setup-cluster.sh && 
               ./setup-telemetry-table.sh"
    restart: "no"
    networks:
      - citus-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./infrastructure/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    restart: unless-stopped

networks:
  citus-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  citus-coordinator-data:
  citus-worker1-data:
  citus-worker2-data: